language: php
php:
  - 7.1
  - 7.2
  - 7.3

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - libxml2-utils

services:
  - postgresql

env:
  global:
  - TEST_JS=FALSE
  - CORE_BRANCH=master
  matrix:
  - DB=sqlite

matrix:
  include:
    - php: 7.1
      env: "DB=mysql TEST_JS=TRUE"
    fast_finish: true

branches:
  only:
  - master
  - "/^stable\\d+(\\.\\d+)?+(\\.\\d+)?$/"
  - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/

cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/.npm"

before_install:
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then npm install; fi"

  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core
  - mv recommendations core/apps/

before_script:
  # Set up core
  - php -f core/occ maintenance:install --database-name nc_autotest --database-user nc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''

  # Set up app
  - php -f core/occ app:enable recommendations
  - cd core/apps/recommendations

script:
  # Check info.xml schema validity
  - wget https://apps.nextcloud.com/schema/apps/info.xsd
  - xmllint appinfo/info.xml --schema info.xsd --noout
  - rm info.xsd

  # Run server's app code checker
  - php ../../occ app:check-code recommendations

  # Build JS
  - sh -c "if [ '$TEST_JS' = 'TRUE' ]; then npm run build; fi"
